GET http://localhost:4000/api/order

###

GET http://localhost:4000/api/order/:id
Content-Type: application/json

{
    "_id": "60a767ce3b59f07246dc95d4"
}

###

POST http://localhost:4000/api/order
Content-Type: application/json

{
    "orderItems": [
        {
            "product": "60a77166532290e262b50946",
            "qty": 1
        },
        {
            "product": "60a7732b532290e262b5094a",
            "qty": 3
        }
    ],
    "address": {
        "phone": "07217897979787",
        "street": "yoyoyoyo",
        "zipcode": "12345",
        "city": "NYYYYASTE"
    },
    "totalprice": "1999", 
    "orderProducts": "60a544da597058b62ff8fed1", 
    "isSent": false
}

###

PUT http://localhost:4000/api/order/:id 
Content-Type: application/json

{
    "orderItem": [],
    "address": {
        "phone": "072177",
        "street": "Hej",
        "zipcode": "12345",
        "city": "SkenEEEE"
    },
    "totalprice": "1000", 
    "orderProducts": "60a767ce3b59f07246dc95d4", 
    "isSent": false
}
