GET http://localhost:4000/api/order

###

GET http://localhost:4000/api/order/:id
Content-Type: application/json

{
    "_id": ""
}

###

POST http://localhost:4000/api/order
Content-Type: application/json

{
    "phone": "0721773030",
    "street": "HabYYYYYYYY", 
    "zipcode": 51163,
    "city": "Haby",
    "totalprice": "1000", 
    "orderProducts": "60a544da597058b62ff8fed1", 
    "isSent": true
}

###

PUT http://localhost:4000/api/order/:id 
Content-Type: application/json

{
    "phone": 072,
    "street": "Ha", 
    "zipcode": 51163,
    "city": "Ha",
    "totalprice": "1000", 
    "orderProducts": "60a544da597058b62ff8fed1", 
    "isSent": true,
    "_id": "60a6254dcf7876507e4c85be"
}
