GET http://localhost:4000/api/order

###

GET http://localhost:4000/api/order/60b740bde727857f4fe692fd

###

GET http://localhost:4000/api/order/user/:id

###

POST http://localhost:4000/api/order
Content-Type: application/json

{
    "orderItems": [
        {
            "product": {
                "_id": "60a7744c532290e262b50950",
                "title": "PRINTED CHIFFON SKIRT",
                "description": "Printed midi chiffon skirt with a gently pleated finish. Concealed zipper at the side. Length of skirt: 83.5cm / 33.3",
                "price": "429",
                "imageUrl": "prod8.png",
                "qty": "10",
                "category": ["Skirts"]
            },
            "qty": 1
        },
        {
            "product": {
                "_id": "60a7732b532290e262b5094a",
                "title": "TAILORED BLAZER",
                "description": "Tailored blazer featuring a cinched waistline and shoulder pads for a subtle hourglass silhouette.",
                "price": "629",
                "imageUrl": "prod3.png",
                "qty": "2",
                "category": ["Blazers"]
            },
            "qty": 3
        }
    ],
    "address": {
        "phone": "0721773030",
        "street": "yoyoyoyo",
        "zipcode": "12345",
        "city": "NYYYYASTE"
    },
    "totalprice": "1999", 
    "isSent": false,
    "delivery": { 
        "company": "Postnord",
        "price": 145,
        "time": 24,
        "_id": "60abaa9b1f828d61f4829b88"
    }
}

###

PUT http://localhost:4000/api/order/:id 
Content-Type: application/json

{
    "_id": "60b740bde727857f4fe692fd",
    "isSent": true
}
